# OpenCellID API Ingestion

This section retrieves telecom cell tower data from the OpenCellID REST API.

The API provides network information such as:

- Cell ID
- MCC and MNC
- LAC / TAC
- Radio technology
- Latitude and longitude
- Coverage range
- Number of samples

The data will be retrieved for a selected geographic area in Egypt and later loaded into the staging layer for use in the Telecom Data Warehouse.

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 26.2.1 is available.
You should consider upgrading via the 'c:\Users\DELL\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [2]:
pip install requests

Requirement already satisfied: requests in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (2.34.2)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from requests) (2026.7.22)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from requests) (3.5.1)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 26.2.1 is available.
You should consider upgrading via the 'c:\Users\DELL\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [3]:
import requests

API_KEY = "pk.8a11fb04b102223fe2dcaf40ac842489"

url = "https://opencellid.org/cell/get"

params = {
    "key": API_KEY,
    "mcc": 260,
    "mnc": 2,
    "lac": 10250,
    "cellid": 26511,
    "radio": "UMTS",
    "format": "json"
}

response = requests.get(url, params=params)

print("Status Code:", response.status_code)
print(response.text)

Status Code: 200
{"lat":52.2316,"lon":21.0119,"mcc":260,"mnc":2,"lac":10250,"cellid":26511,"averageSignalStrength":0,"range":858,"samples":1,"changeable":1,"radio":"UMTS","rnc":0,"cid":0,"tac":0,"sid":0,"nid":0,"bid":0,"message":null}

In [4]:
import pandas as pd

data = response.json()

df = pd.DataFrame([data])

df

,lat,lon,mcc,mnc,lac,cellid,averageSignalStrength,range,samples,changeable,radio,rnc,cid,tac,sid,nid,bid,message
0,52.2316,21.0119,260,2,10250,26511,0,858,1,1,UMTS,0,0,0,0,0,0,None

In [5]:
df.shape

(1, 18)

In [6]:
import requests
import pandas as pd
import time

API_KEY = "pk.8a11fb04b102223fe2dcaf40ac842489"

url = "https://opencellid.org/cell/getInArea"

# Small area in Cairo
bbox = "30.030,31.220,30.045,31.235"

all_cells = []

limit = 50
offset = 0

for page in range(20):   # 20 pages × 50 = up to 1000 rows

    params = {
        "key": API_KEY,
        "BBOX": bbox,
        "mcc": 602,       # Egypt
        "limit": limit,
        "offset": offset,
        "format": "json"
    }

    response = requests.get(url, params=params)

    print(
        f"Page {page + 1} | "
        f"Status: {response.status_code} | "
        f"Offset: {offset}"
    )

    if response.status_code != 200:
        print(response.text)
        break

    data = response.json()

    # Check API error responses
    if "error" in data:
        print(data)
        break

    cells = data.get("cells", [])

    if not cells:
        print("No more records.")
        break

    all_cells.extend(cells)

    print("Rows received:", len(cells))
    print("Total rows:", len(all_cells))

    if len(cells) < limit:
        break

    offset += limit

    # Don't hit API too aggressively
    time.sleep(0.5)

Page 1 | Status: 200 | Offset: 0
Rows received: 50
Total rows: 50
Page 2 | Status: 200 | Offset: 50
Rows received: 50
Total rows: 100
Page 3 | Status: 200 | Offset: 100
Rows received: 50
Total rows: 150
Page 4 | Status: 200 | Offset: 150
Rows received: 50
Total rows: 200
Page 5 | Status: 200 | Offset: 200
Rows received: 50
Total rows: 250
Page 6 | Status: 200 | Offset: 250
Rows received: 50
Total rows: 300
Page 7 | Status: 200 | Offset: 300
Rows received: 50
Total rows: 350
Page 8 | Status: 200 | Offset: 350
Rows received: 50
Total rows: 400
Page 9 | Status: 200 | Offset: 400
Rows received: 50
Total rows: 450
Page 10 | Status: 200 | Offset: 450
Rows received: 50
Total rows: 500
Page 11 | Status: 200 | Offset: 500
Rows received: 50
Total rows: 550
Page 12 | Status: 200 | Offset: 550
Rows received: 50
Total rows: 600
Page 13 | Status: 200 | Offset: 600
Rows received: 50
Total rows: 650
Page 14 | Status: 200 | Offset: 650
Rows received: 50
Total rows: 700
Page 15 | Status: 200 | Offset: 700
Rows received: 50
Total rows: 750
Page 16 | Status: 200 | Offset: 750
Rows received: 50
Total rows: 800
Page 17 | Status: 200 | Offset: 800
Rows received: 47
Total rows: 847

In [7]:
import pandas as pd
from datetime import datetime, timezone

# Convert API response to a DataFrame
df = pd.DataFrame(all_cells)

# Add ingestion metadata
df["ingestion_timestamp"] = datetime.now(timezone.utc)
df["source_system"] = "OpenCellID"

# Preview the data
df.head()

,lat,lon,mcc,mnc,lac,cellid,averageSignalStrength,range,samples,changeable,radio,rnc,cid,tac,sid,nid,bid,ingestion_timestamp,source_system
0,30.03,31.233,602,1,6242,865964,0,1000,1,1,UMTS,0,0,0,0,0,0,2026-09-21 12:27:50.774681+00:00,OpenCellID
1,30.03,31.233,602,2,52102,11821,0,1000,1,1,GSM,0,0,0,0,0,0,2026-09-21 12:27:50.774681+00:00,OpenCellID
2,30.03,31.223,602,2,52102,6085,0,1000,1,1,GSM,0,0,0,0,0,0,2026-09-21 12:27:50.774681+00:00,OpenCellID
3,30.03,31.232,602,2,11130,26015262,0,1000,1,1,LTE,0,0,11130,0,0,0,2026-09-21 12:27:50.774681+00:00,OpenCellID
4,30.03,31.227,602,3,32062,13526917,0,1000,1,1,UMTS,0,0,0,0,0,0,2026-09-21 12:27:50.774681+00:00,OpenCellID

## Data Overview

Check the number of rows, columns, and data types.

In [8]:
# Check dataset size
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 847
Columns: 19

In [9]:
# Check column names
print(df.columns.tolist())

['lat', 'lon', 'mcc', 'mnc', 'lac', 'cellid', 'averageSignalStrength', 'range', 'samples', 'changeable', 'radio', 'rnc', 'cid', 'tac', 'sid', 'nid', 'bid', 'ingestion_timestamp', 'source_system']

In [10]:
# Check data types and null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 847 entries, 0 to 846
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   lat                    847 non-null    float64
 1   lon                    847 non-null    float64
 2   mcc                    847 non-null    int64
 3   mnc                    847 non-null    int64
 4   lac                    847 non-null    int64
 5   cellid                 847 non-null    int64
 6   averageSignalStrength  847 non-null    int64
 7   range                  847 non-null    int64
 8   samples                847 non-null    int64
 9   changeable             847 non-null    int64
 10  radio                  847 non-null    object
 11  rnc                    847 non-null    int64
 12  cid                    847 non-null    int64
 13  tac                    847 non-null    int64
 14  sid                    847 non-null    int64
 15  nid                    847 non-null    int64
 16  bid                    847 non-null    int64
 17  ingestion_timestamp    847 non-null    datetime64[us, UTC]
 18  source_system          847 non-null    object
dtypes: datetime64[us, UTC](1), float64(2), int64(14), object(2)
memory usage: 125.9+ KB

## Basic Data Transformation

Before loading the data into the staging layer, a small amount of preprocessing is applied.

This step includes:

- Removing unnecessary columns
- Checking duplicate records
- Reviewing data types
- Converting selected columns to the correct data types
- Saving the cleaned raw data using the current date

In [11]:
import pandas as pd
from datetime import datetime
from pathlib import Path

# Remove unnecessary column
if "source_system" in df.columns:
    df = df.drop(columns=["source_system"])

In [12]:
# Check duplicate rows
duplicate_count = df.duplicated().sum()

print("Duplicate Rows:", duplicate_count)

Duplicate Rows: 0

In [13]:
# Remove duplicate rows
df = df.drop_duplicates()

In [14]:
# Check data types
print("\nData Types:")
print(df.dtypes)

Data Types:
lat                                  float64
lon                                  float64
mcc                                    int64
mnc                                    int64
lac                                    int64
cellid                                 int64
averageSignalStrength                  int64
range                                  int64
samples                                int64
changeable                             int64
radio                                 object
rnc                                    int64
cid                                    int64
tac                                    int64
sid                                    int64
nid                                    int64
bid                                    int64
ingestion_timestamp      datetime64[us, UTC]
dtype: object

In [15]:
# Convert selected columns to numeric
numeric_columns = [
    "lat",
    "lon",
    "mcc",
    "mnc",
    "lac",
    "cellid",
    "range",
    "samples"
]

for column in numeric_columns:
    if column in df.columns:
        df[column] = pd.to_numeric(
            df[column],
            errors="coerce"
        )

In [16]:
# Preview cleaned data
df.head()

,lat,lon,mcc,mnc,lac,cellid,averageSignalStrength,range,samples,changeable,radio,rnc,cid,tac,sid,nid,bid,ingestion_timestamp
0,30.03,31.233,602,1,6242,865964,0,1000,1,1,UMTS,0,0,0,0,0,0,2026-09-21 12:27:50.774681+00:00
1,30.03,31.233,602,2,52102,11821,0,1000,1,1,GSM,0,0,0,0,0,0,2026-09-21 12:27:50.774681+00:00
2,30.03,31.223,602,2,52102,6085,0,1000,1,1,GSM,0,0,0,0,0,0,2026-09-21 12:27:50.774681+00:00
3,30.03,31.232,602,2,11130,26015262,0,1000,1,1,LTE,0,0,11130,0,0,0,2026-09-21 12:27:50.774681+00:00
4,30.03,31.227,602,3,32062,13526917,0,1000,1,1,UMTS,0,0,0,0,0,0,2026-09-21 12:27:50.774681+00:00

## Data Quality Check

Validate the dataset after the basic transformation.

In [17]:
# Check duplicates after cleaning
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [18]:
# Check final dataset size
print("\nRows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 847
Columns: 18

In [19]:
# Check final data types
print("\nFinal Data Types:")
print(df.dtypes)

Final Data Types:
lat                                  float64
lon                                  float64
mcc                                    int64
mnc                                    int64
lac                                    int64
cellid                                 int64
averageSignalStrength                  int64
range                                  int64
samples                                int64
changeable                             int64
radio                                 object
rnc                                    int64
cid                                    int64
tac                                    int64
sid                                    int64
nid                                    int64
bid                                    int64
ingestion_timestamp      datetime64[us, UTC]
dtype: object

In [20]:
# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
lat                      0
lon                      0
mcc                      0
mnc                      0
lac                      0
cellid                   0
averageSignalStrength    0
range                    0
samples                  0
changeable               0
radio                    0
rnc                      0
cid                      0
tac                      0
sid                      0
nid                      0
bid                      0
ingestion_timestamp      0
dtype: int64

## Save Processed Raw Data

Save the prepared API data as a Parquet file using the current date.

In [21]:
# Create output directory
output_path = Path("data/raw/network/opencellid")
output_path.mkdir(parents=True, exist_ok=True)

# Current date
today = datetime.now().strftime("%Y-%m-%d")

# File name
file_name = f"opencellid_{today}.parquet"

full_path = output_path / file_name

# Save data
df.to_parquet(
    full_path,
    index=False
)

print("File saved:", full_path)

File saved: data\raw\network\opencellid\opencellid_2026-09-21.parquet

In [22]:
df = df.rename(
    columns={
        "averageSignalStrength": "average_signal_strength"
    }
)

## Load Data into PostgreSQL Staging

Load the prepared OpenCellID data into the PostgreSQL staging table.

In [23]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (2.9.13)
Requirement already satisfied: sqlalchemy in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (2.0.54)
Requirement already satisfied: greenlet>=1 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (3.5.6)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\appdata\roaming\python\python310\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 26.2.1 is available.
You should consider upgrading via the 'c:\Users\DELL\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [24]:
from sqlalchemy import create_engine

# Connect to PostgreSQL running inside Docker
engine = create_engine(
    "postgresql+psycopg2://postgres:123@localhost:5433/telecom_dw"
)

# Load data into the staging table
df.to_sql(
    name="network_cells",
    con=engine,
    schema="staging",
    if_exists="append",
    index=False
)

print("Data loaded successfully.")

Data loaded successfully.