## CRM Customer Data Ingestion

Load customer data from the CRM source and prepare it for the PostgreSQL staging layer.

In [1]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 26.2.1 is available.
You should consider upgrading via the 'c:\Users\DELL\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [2]:
import pandas as pd

file_path = '../data/raw/crm/Telco_customer_churn.xlsx'

# Load CRM customer data
crm_df = pd.read_excel(file_path)

print("Rows:", crm_df.shape[0])
print("Columns:", crm_df.shape[1])

crm_df.head()

Rows: 7043
Columns: 33

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

## CRM Data Profiling

Review the CRM dataset structure, data types, missing values, and duplicate records before loading it into PostgreSQL.

In [3]:
# Check dataset shape
print("Rows:", crm_df.shape[0])
print("Columns:", crm_df.shape[1])

Rows: 7043
Columns: 33

In [4]:
# Check column names
print("\nColumns:")
print(crm_df.columns.tolist())

Columns:
['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code', 'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months', 'Phone Service', 'Multiple Lines', 'Internet Service', 'Online Security', 'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value', 'Churn Score', 'CLTV', 'Churn Reason']

In [5]:
# Check data types
print("\nData Types:")
print(crm_df.dtypes)

Data Types:
CustomerID            object
Count                  int64
Country               object
State                 object
City                  object
Zip Code               int64
Lat Long              object
Latitude             float64
Longitude            float64
Gender                object
Senior Citizen        object
Partner               object
Dependents            object
Tenure Months          int64
Phone Service         object
Multiple Lines        object
Internet Service      object
Online Security       object
Online Backup         object
Device Protection     object
Tech Support          object
Streaming TV          object
Streaming Movies      object
Contract              object
Paperless Billing     object
Payment Method        object
Monthly Charges      float64
Total Charges         object
Churn Label           object
Churn Value            int64
Churn Score            int64
CLTV                   int64
Churn Reason          object
dtype: object

In [6]:
# Check missing values
print("\nMissing Values:")
print(crm_df.isnull().sum())

Missing Values:
CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [7]:
# Check duplicate rows
print("\nDuplicate Rows:")
print(crm_df.duplicated().sum())

Duplicate Rows:
0

## Basic CRM Transformation

Apply light preprocessing before loading the CRM data into the staging layer.

In [8]:
# Standardize column names
crm_df.columns = (
    crm_df.columns
    .str.strip()
    .str.replace(" ", "_")
    .str.replace("-", "_")
    .str.lower()
)

In [9]:
# Convert TotalCharges to numeric
crm_df["total_charges"] = pd.to_numeric(
    crm_df["total_charges"],
    errors="coerce"
)

In [10]:
# check 
crm_df.head()

,customerid,count,country,state,city,zip_code,lat_long,latitude,longitude,gender,...,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn_label,churn_value,churn_score,cltv,churn_reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes,1,89,5340,Competitor had better devices

In [11]:
crm_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customerid         7043 non-null   object
 1   count              7043 non-null   int64
 2   country            7043 non-null   object
 3   state              7043 non-null   object
 4   city               7043 non-null   object
 5   zip_code           7043 non-null   int64
 6   lat_long           7043 non-null   object
 7   latitude           7043 non-null   float64
 8   longitude          7043 non-null   float64
 9   gender             7043 non-null   object
 10  senior_citizen     7043 non-null   object
 11  partner            7043 non-null   object
 12  dependents         7043 non-null   object
 13  tenure_months      7043 non-null   int64
 14  phone_service      7043 non-null   object
 15  multiple_lines     7043 non-null   object
 16  internet_service   7043 non-null   object
 17  online_security    7043 non-null   object
 18  online_backup      7043 non-null   object
 19  device_protection  7043 non-null   object
 20  tech_support       7043 non-null   object
 21  streaming_tv       7043 non-null   object
 22  streaming_movies   7043 non-null   object
 23  contract           7043 non-null   object
 24  paperless_billing  7043 non-null   object
 25  payment_method     7043 non-null   object
 26  monthly_charges    7043 non-null   float64
 27  total_charges      7032 non-null   float64
 28  churn_label        7043 non-null   object
 29  churn_value        7043 non-null   int64
 30  churn_score        7043 non-null   int64
 31  cltv               7043 non-null   int64
 32  churn_reason       1869 non-null   object
dtypes: float64(4), int64(6), object(23)
memory usage: 1.8+ MB

## Handle Missing Values

Check missing values in the CRM dataset and apply appropriate handling based on the business meaning of each column.

In [12]:
# Check missing values
missing_values = crm_df.isnull().sum()

print( missing_values[missing_values > 0])

total_charges      11
churn_reason     5174
dtype: int64

## Missing Value Treatment

Missing values are handled according to their business meaning:

- `churn_reason`: missing values are expected for customers who did not churn, so they are filled with `Not Applicable`.

In [13]:
# Fill missing churn reasons
crm_df["churn_reason"] = crm_df["churn_reason"].fillna(
    "Not Applicable"
)

In [14]:
# Inspect rows with missing total_charges
missing_total = crm_df[crm_df["total_charges"].isnull()]

missing_total[
    [
        "customerid",
        "tenure_months",
        "monthly_charges",
        "total_charges",
        "contract",
        "churn_label"
    ]
]

,customerid,tenure_months,monthly_charges,total_charges,contract,churn_label
2234,4472-LVYGI,0,52.55,NaN,Two year,No
2438,3115-CZMZD,0,20.25,NaN,Two year,No
2568,5709-LVOEQ,0,80.85,NaN,Two year,No
2667,4367-NUYAO,0,25.75,NaN,Two year,No
2856,1371-DWPAZ,0,56.05,NaN,Two year,No
4331,7644-OMVMY,0,19.85,NaN,Two year,No
4687,3213-VVOLG,0,25.35,NaN,Two year,No
5104,2520-SGTTA,0,20.00,NaN,Two year,No
5719,2923-ARZLG,0,19.70,NaN,One year,No
6772,4075-WKNIU,0,73.35,NaN,Two year,No
6840,2775-SEFEE,0,61.90,NaN,Two year,No

## Missing Total Charges Analysis

The missing values in `total_charges` were investigated before applying any treatment.

All affected customers have `tenure_months = 0`, which indicates that they are new customers with no completed billing history yet.

Therefore, the missing values are considered valid business cases rather than data quality errors.

In [15]:
# Fill missing total charges for new customers
crm_df["total_charges"] = crm_df["total_charges"].fillna(0)

In [16]:
# Verify missing values

crm_df.isnull().sum()

customerid           0
count                0
country              0
state                0
city                 0
zip_code             0
lat_long             0
latitude             0
longitude            0
gender               0
senior_citizen       0
partner              0
dependents           0
tenure_months        0
phone_service        0
multiple_lines       0
internet_service     0
online_security      0
online_backup        0
device_protection    0
tech_support         0
streaming_tv         0
streaming_movies     0
contract             0
paperless_billing    0
payment_method       0
monthly_charges      0
total_charges        0
churn_label          0
churn_value          0
churn_score          0
cltv                 0
churn_reason         0
dtype: int64

## Load CRM Data to PostgreSQL Staging

Load the cleaned CRM customer dataset into the PostgreSQL staging layer for downstream dbt transformations.

In [17]:
from datetime import datetime, timezone

# Add ingestion timestamp
crm_df["ingestion_timestamp"] = datetime.now(timezone.utc)

In [18]:
print(crm_df.columns.tolist())

['customerid', 'count', 'country', 'state', 'city', 'zip_code', 'lat_long', 'latitude', 'longitude', 'gender', 'senior_citizen', 'partner', 'dependents', 'tenure_months', 'phone_service', 'multiple_lines', 'internet_service', 'online_security', 'online_backup', 'device_protection', 'tech_support', 'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing', 'payment_method', 'monthly_charges', 'total_charges', 'churn_label', 'churn_value', 'churn_score', 'cltv', 'churn_reason', 'ingestion_timestamp']

In [19]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:123@localhost:5433/telecom_dw"
)

In [20]:
# Load CRM data into PostgreSQL staging
crm_df.to_sql(
    name="customers",
    con=engine,
    schema="staging",
    if_exists="append",
    index=False
)

print("CRM data loaded successfully into staging.customers")

CRM data loaded successfully into staging.customers