## Billing Data Generation

Generate realistic monthly billing transactions from the CRM customer dataset using the existing customer IDs and billing attributes.

In [1]:
import pandas as pd

crm_df = pd.read_excel(
    "../data/raw/crm/Telco_customer_churn.xlsx"
)

crm_df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [2]:
# Standardize column names
crm_df.columns = (
    crm_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print(crm_df.columns.tolist())

['customerid', 'count', 'country', 'state', 'city', 'zip_code', 'lat_long', 'latitude', 'longitude', 'gender', 'senior_citizen', 'partner', 'dependents', 'tenure_months', 'phone_service', 'multiple_lines', 'internet_service', 'online_security', 'online_backup', 'device_protection', 'tech_support', 'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing', 'payment_method', 'monthly_charges', 'total_charges', 'churn_label', 'churn_value', 'churn_score', 'cltv', 'churn_reason']

In [4]:
# Select billing-related customer attributes
billing_base = crm_df[
    [
        "customerid",
        "contract",
        "payment_method",
        "monthly_charges",
        "total_charges",
        "tenure_months"
    ]
].copy()

## Generate Monthly Billing Transactions

Create monthly billing records for each customer based on tenure and monthly charges.

In [5]:
from datetime import datetime
import random

billing_rows = []

for _, row in billing_base.iterrows():

    customer_id = row["customerid"]
    tenure = int(row["tenure_months"])
    monthly_charge = float(row["monthly_charges"])
    payment_method = row["payment_method"]
    contract = row["contract"]

    # Generate one billing record for each month of tenure
    for month_number in range(1, tenure + 1):

        invoice_date = pd.Timestamp("2024-01-01") + pd.DateOffset(months=month_number - 1)

        due_date = invoice_date + pd.Timedelta(days=14)

        payment_status = random.choice([
            "Paid",
            "Paid",
            "Paid",
            "Pending",
            "Late"
        ])

        late_fee = 0

        if payment_status == "Late":
            late_fee = round(monthly_charge * 0.05, 2)

        total_amount = round(monthly_charge + late_fee, 2)

        billing_rows.append({
            "customer_id": customer_id,
            "invoice_date": invoice_date,
            "due_date": due_date,
            "billing_period": invoice_date.strftime("%Y-%m"),
            "monthly_charges": monthly_charge,
            "total_amount": total_amount,
            "payment_status": payment_status,
            "payment_method": payment_method,
            "late_fee": late_fee,
            "contract": contract
        })

In [6]:
# Create billing transactions dataframe
billing_df = pd.DataFrame(billing_rows)

print(billing_df.shape)

billing_df.head()

(227990, 10)

,customer_id,invoice_date,due_date,billing_period,monthly_charges,total_amount,payment_status,payment_method,late_fee,contract
0,3668-QPYBK,2024-01-01,2024-01-15,2024-01,53.85,53.85,Paid,Mailed check,0.00,Month-to-month
1,3668-QPYBK,2024-02-01,2024-02-15,2024-02,53.85,56.54,Late,Mailed check,2.69,Month-to-month
2,9237-HQITU,2024-01-01,2024-01-15,2024-01,70.70,70.70,Paid,Electronic check,0.00,Month-to-month
3,9237-HQITU,2024-02-01,2024-02-15,2024-02,70.70,70.70,Pending,Electronic check,0.00,Month-to-month
4,9305-CDSKC,2024-01-01,2024-01-15,2024-01,99.65,104.63,Late,Electronic check,4.98,Month-to-month

## Prepare Billing Data

Add billing metadata and validate the generated billing transactions before loading them into SQL Server.

In [8]:
# Add billing identifier
billing_df.insert(
    0,
    "billing_id",
    range(1, len(billing_df) + 1)
)

# Add creation timestamp
billing_df["created_at"] = pd.Timestamp.now()

In [9]:
# Review generated billing data
print("Shape:")
print(billing_df.shape)

print("\nMissing Values:")
print(billing_df.isnull().sum())

print("\nDuplicate Rows:")
print(billing_df.duplicated().sum())

print("\nData Types:")
print(billing_df.dtypes)

billing_df.head()

Shape:
(227990, 12)

Missing Values:
billing_id         0
customer_id        0
invoice_date       0
due_date           0
billing_period     0
monthly_charges    0
total_amount       0
payment_status     0
payment_method     0
late_fee           0
contract           0
created_at         0
dtype: int64

Duplicate Rows:
0

Data Types:
billing_id                  int64
customer_id                object
invoice_date       datetime64[ns]
due_date           datetime64[ns]
billing_period             object
monthly_charges           float64
total_amount              float64
payment_status             object
payment_method             object
late_fee                  float64
contract                   object
created_at         datetime64[us]
dtype: object

,billing_id,customer_id,invoice_date,due_date,billing_period,monthly_charges,total_amount,payment_status,payment_method,late_fee,contract,created_at
0,1,3668-QPYBK,2024-01-01,2024-01-15,2024-01,53.85,53.85,Paid,Mailed check,0.00,Month-to-month,2026-09-19 18:26:22.502139
1,2,3668-QPYBK,2024-02-01,2024-02-15,2024-02,53.85,56.54,Late,Mailed check,2.69,Month-to-month,2026-09-19 18:26:22.502139
2,3,9237-HQITU,2024-01-01,2024-01-15,2024-01,70.70,70.70,Paid,Electronic check,0.00,Month-to-month,2026-09-19 18:26:22.502139
3,4,9237-HQITU,2024-02-01,2024-02-15,2024-02,70.70,70.70,Pending,Electronic check,0.00,Month-to-month,2026-09-19 18:26:22.502139
4,5,9305-CDSKC,2024-01-01,2024-01-15,2024-01,99.65,104.63,Late,Electronic check,4.98,Month-to-month,2026-09-19 18:26:22.502139

## Load Billing Data to SQL Server

Load the generated billing transactions into the SQL Server billing source table.

In [10]:
# Prepare columns to match the SQL Server table
billing_load_df = billing_df.drop(
    columns=["billing_id", "contract"],
    errors="ignore"
)

print(billing_load_df.columns.tolist())

['customer_id', 'invoice_date', 'due_date', 'billing_period', 'monthly_charges', 'total_amount', 'payment_status', 'payment_method', 'late_fee', 'created_at']

In [11]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# SQL Server connection
connection_string = quote_plus(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=localhost;"
    "DATABASE=telecom_source_db;"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)

sqlserver_engine = create_engine(
    f"mssql+pyodbc:///?odbc_connect={connection_string}",
    fast_executemany=True
)

In [12]:
# Load billing transactions into SQL Server
billing_load_df.to_sql(
    name="billing_transactions",
    con=sqlserver_engine,
    schema="dbo",
    if_exists="append",
    index=False,
    chunksize=5000
)

print("Billing data loaded successfully into SQL Server.")

Billing data loaded successfully into SQL Server.

In [13]:
# Extract billing data from SQL Server
billing_source_df = pd.read_sql(
    """
    SELECT *
    FROM dbo.billing_transactions
    """,
    sqlserver_engine
)

print(billing_source_df.shape)
billing_source_df.head()

(227990, 12)

,billing_id,customer_id,invoice_date,due_date,billing_period,monthly_charges,total_amount,payment_status,payment_method,late_fee,contract,created_at
0,1,3668-QPYBK,2024-01-01,2024-01-15,2024-01,53.85,53.85,Paid,Mailed check,0.00,None,2026-09-19 18:26:22.502139
1,2,3668-QPYBK,2024-02-01,2024-02-15,2024-02,53.85,56.54,Late,Mailed check,2.69,None,2026-09-19 18:26:22.502139
2,3,9237-HQITU,2024-01-01,2024-01-15,2024-01,70.70,70.70,Paid,Electronic check,0.00,None,2026-09-19 18:26:22.502139
3,4,9237-HQITU,2024-02-01,2024-02-15,2024-02,70.70,70.70,Pending,Electronic check,0.00,None,2026-09-19 18:26:22.502139
4,5,9305-CDSKC,2024-01-01,2024-01-15,2024-01,99.65,104.63,Late,Electronic check,4.98,None,2026-09-19 18:26:22.502139

In [14]:
from datetime import datetime, timezone

# Add ingestion timestamp
billing_source_df["ingestion_timestamp"] = datetime.now(timezone.utc)

In [15]:
from datetime import datetime, timezone

# Add ingestion timestamp
billing_source_df["ingestion_timestamp"] = datetime.now(timezone.utc)

In [17]:
# Load billing data into PostgreSQL staging
from sqlalchemy import create_engine

# Create PostgreSQL connection
postgres_engine = create_engine(
    "postgresql+psycopg2://postgres:123@localhost:5433/telecom_dw"
)

billing_source_df.to_sql(
    name="billing",
    con=postgres_engine,
    schema="staging",
    if_exists="append",
    index=False,
    chunksize=5000
)

print("Billing data loaded successfully into staging.billing")

Billing data loaded successfully into staging.billing